############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
# Frontend build
FROM nginx:alpine

LABEL maintainer "Elias De Hondt"
LABEL version "1.0"
LABEL description ""
LABEL org.opencontainers.image.description ""

